### ISSUE TITLE
Multiline strings break, linebreaks of multiline strings should be ignored?

### ISSUE THREAD

**Issue by subsoap** [britzl/defold-richtext#17]
```
	local text = [[
	<size=1>Lara</size><br/>
	<size=0.7>Well, hello there!</size><br/>
	<size=0.7>What do we have here?</size><img=icons:waiting/>]]
```
Becomes

![2018-03-01 21_56_28-vn](https://user-images.githubusercontent.com/409170/36885381-6df097d0-1d9b-11e8-8b70-d4045c184d49.png)

It should be

![2018-03-01 21_57_28-vn](https://user-images.githubusercontent.com/409170/36885400-8fa274c0-1d9b-11e8-9c52-226c1cabe92a.png)

Which requires

```
local text = [[<size=1>Lara</size><br/><size=0.7>Well, hello there!</size><br/><size=0.7>What do we have here?</size><img=icons:waiting/>]]
```

It would be nice to be able to format in scripts with multiline strings so it's a little easier to manage.

**Comment by britzl** [comment]
Couldn't you just ignore the `<br/>` tags? Line-breaks (`\n`) are accepted as well.

**Comment by subsoap** [comment]
If I remove the ```<br/>``` tags it looks like this

![2018-03-02 08_21_58-defold editor 2 0 - vn](https://user-images.githubusercontent.com/409170/36909453-d62c5a58-1df2-11e8-8022-40f9389061a4.png)
![2018-03-02 08_21_52-vn](https://user-images.githubusercontent.com/409170/36909458-d973fe96-1df2-11e8-80c2-e37f42587e7d.png)

**Comment by subsoap** [comment]
If I set the size to 1 it looks closer to right, related to that in some way?

![2018-03-02 08_35_33-vn](https://user-images.githubusercontent.com/409170/36910133-b364975e-1df4-11e8-8384-685e51c910a2.png)

Higher scales seem to have more space than they need

![2018-03-02 08_36_23-vn](https://user-images.githubusercontent.com/409170/36910179-da2dc0c2-1df4-11e8-8246-661c6c3c892f.png)

**Comment by britzl** [comment]
Ah, I do not properly handle \r\n. Fixed in 2.5.2

**Comment by subsoap** [comment]
I'm still seeing

![2018-03-02 13_13_04-vn](https://user-images.githubusercontent.com/409170/36922061-7cff92dc-1e1b-11e8-9427-08b3a479a76a.png)

![2018-03-02 13_14_07-vn](https://user-images.githubusercontent.com/409170/36922088-9c04d9d0-1e1b-11e8-9122-9a687c59b30b.png)


 with I think latest release 

```
local text = [[
<size=1>Lara</size><br/>
<size=1.2>Well, hello there!</size><br/>
<size=0.3>What do we have here?</size><img=icons:waiting/>]]

local text = [[<size=1>???</size><br/><size=0.7>Well, hello there!</size><br/><size=0.7>What do we have here?</size><img=icons:waiting/>]]	
```

**Comment by subsoap** [comment]
Happens in example too

![2018-03-02 16_58_21-richtext](https://user-images.githubusercontent.com/409170/36928468-fa235fb8-1e3a-11e8-8468-8beaedaf6e59.png)

```
local text = "<size=0.5>RichText several words to test this</size>Lorem <color=0,0.5,0,1>ipsum </color><img=smileys:zombie/> dolor <color=red>sit </color><color=#ff00ffff>amet, </color><size=1.15><font=Nanum>consectetur </font></size>adipiscing elit.<br/><b>Nunc </b>tincidunt <b><i>mattis</i> libero</b> <i>non viverra</i>.\n\nNullam ornare <img=smileys:hungry></img>accumsan rhoncus.\n\nNunc placerat nibh a purus auctor, id scelerisque massa <size=2>rutrum.</size>"
```

**Comment by britzl** [comment]
Ok, what about now? https://github.com/britzl/defold-richtext/releases/tag/2.5.3

**Comment by subsoap** [comment]
Looks to be fixed!
